### ISSUE TITLE
1.12.2 Combatability?

### ISSUE THREAD

**Issue by PizzaOnFire99125** [Unity-Resource-Pack/Unity-PBR#16]
Hello! It didn't feel right to put this in "Issues" so I put it here. I just have a couple questions about the resource packs- but mainly about 1.12.2 compatibility. Now I could have missed it, but some of your packs have this compatibility and some don't. I was just wondering if you could add this compatibility, or have already done so and it just isn't on the CurseForge page. The following; Unity: Modded, SEUS PTGI, & Unity: Extras; all don't have this, but I'm mainly here on that I can't get the shader/SEUS PTGI, since it only goes down to 1.14.4, yet the main resource pack goes down to 1.12.2. If I would request anything it would just be compatibility for that.

I'm saying this since 1.12.2 is a large hot spot with a lot of mods, and some mods even stopped being made after 1.12.2, it would actually bring a lot more people to the resource pack if you added this compatibility.

**Comment by CyanideX** [comment]
You can try this pack with 1.12 and SEUS PTGI E7.1, [found here](https://www.patreon.com/posts/download-seus-e7-27319525), but don't expect it to work without issues (or work at all). I don't plan to make a version for 1.12, which isn't as popular as you may think, and if I ever have spare time to work on Unity I'd like to focus on updating to newer versions or fixing existing issues. Thank you for your interest in the pack, though!
