### ISSUE TITLE
Chest and Ender Chest textures bugged when using SEUS PTGI HRR 3.

### ISSUE THREAD

**Issue by AetherXSN** [Unity-Resource-Pack/Unity-PBR#17]
**Describe the Issue**
The chest and ender chest textures are bugged, allowing you to see through some parts

**To Reproduce**
Look at any kind of chest.

**Expected Behavior**
Cross shaped gap in the textures. Every side.

**Screenshots**
<img width="480" alt="fhdgfhsgfdgfsdgfdgsfdgsfds" src="https://user-images.githubusercontent.com/109865581/180611906-ab2134b0-dc59-4b86-a17f-cd51764f53de.png">

<img width="480" alt="fasdasdfasdasdfasdffasdasdfsd" src="https://user-images.githubusercontent.com/109865581/180611966-38d40e8e-764d-4bf5-953b-743229337721.png">

**Additional Context**
The only mods i have that change ingame textures in some way are 3D Skin Layers, Quark/Quark Oddities, and Client Tweaks. I'm only using Mod Resources and Unity (Dark Mode). I am using Optifine.

**Comment by CyanideX** [comment]
This is an issue with the alpha layer in Unity PBR. I've been meaning to get to fixing that but just haven't had the time. It's on my todo list, though!

**Comment by AetherXSN** [comment]
Ah, ok. I also should've stated that vines are also bugged out, and that Alternate Blocks bugs out sand.

<img width="480" alt="adrsdfagsdfgfsdgfdgfsgffgfdg" src="https://user-images.githubusercontent.com/109865581/180644046-74a8ac5b-e161-4b11-b3ae-1865903cf9bb.png">

<img width="480" alt="waaaaaaaaaaaaa" src="https://user-images.githubusercontent.com/109865581/180644050-e4d2fbca-947f-407e-b2a3-7ae531fd3ee1.png">

**Comment by CyanideX** [comment]
Still an issue. 😝 Let's leave it open.

**Comment by AetherXSN** [comment]
oops lol

**Comment by AetherXSN** [comment]
I think I found a fix. Disabling POM.

**Comment by AetherXSN** [comment]
It worked on GFME V1.7 tho, and its a PTGI edit so maybe there's something different.

**Comment by AetherXSN** [comment]
Yea the issue was POM.
