### ISSUE TITLE
[1.16.1] Unity PBR Materials (SEUS Shader Support)

### ISSUE THREAD

**Issue by skydoesminecraft1** [Unity-Resource-Pack/Unity-PBR#3]
Note: If you're going to make something that has shader support, you should try contacting the shader creator that it was made for, and try to work together to make it happen!

Just a few minutes in and messing around with settings, I've come to notice that it seems the reflections on objects like iron/diamond/gold blocks only reflect properly if the Metalness option is set to A. I'm using E12 as suggested and they don't work properly or entirely how it was programmed until I changed it from g (based off the provided screenshot you guys provided above)

Metalness - A/G example:

https://imgur.com/a/TcoSJJJ

 

With Metalness - G, the iron and gold block is hardly affected at all to the point that it looks like it doesn't even work on them (tho it does, at certain angles and darker areas.)

 

I've also noticed that reflections on reflective objects, like an iron block, don't work underwater regardless of what option I choose.

 

Such as this weird visual effect that only lets reflections work to a certain distance and oversaturated red. 

Examples:

https://streamable.com/m7sri6

https://streamable.com/5gsklk

https://streamable.com/k2ujqr

 

Specs:

Minecraft version 1.16.1

Unity Base Resource Pack, Unity Dark Resource Pack, Unity PBR Shader Support Resource Pack

SEUS PTGI E12

CPU- AMD FX-8370 BE

GPU- Asus GTX 1060 6GB OC (dual fan edition)

RAM- 16GB of 2400MHz DDR3

Monitor- Acer 144Hz Gaming Monitor (not sure which model exactly)

 

Anything else I need to know or any questions that want to be asked, please do!

Wish we could get Sonic Ether involved in this thread 😂

 

I'm assuming there's a lot of things that are caused by the shaders and the resource pack separately, inadvertently causing more problems with each other, but this was only a few minutes of fooling around.

**Comment by CyanideX** [comment]
I don't see the problem. This is what it looks like for me:

![2021-01-24_14 52 21](https://user-images.githubusercontent.com/3106700/105646389-90879300-5e54-11eb-9bda-d89617340a64.png)
![2021-01-24_14 53 05](https://user-images.githubusercontent.com/3106700/105646391-91202980-5e54-11eb-84b5-f2dff8017b81.png)
![2021-01-24_14 53 15](https://user-images.githubusercontent.com/3106700/105646392-92515680-5e54-11eb-8f13-77115cc368dc.png)


And here is a comparison between SEUS HRR and SEUS PTGI:

![2021-01-24_14 56 47](https://user-images.githubusercontent.com/3106700/105646398-9d0beb80-5e54-11eb-91ca-f51b35d4cd75.png)
![2021-01-24_14 57 08](https://user-images.githubusercontent.com/3106700/105646400-9da48200-5e54-11eb-8087-185426655f11.png)

**Comment by CyanideX** [comment]
I should note that, in some cases, some light source blocks will fail to render below 1 block level, as seen here:

![2021-01-24_14 54 10](https://user-images.githubusercontent.com/3106700/105646444-ce84b700-5e54-11eb-802a-cb8f60e668ac.png)

Notice how there is only one block being reflected in the surface of the iron floor. Switching shaders on and off can fix that. And yes, there is an viewing angle limit on the sources being reflected.

**Comment by CyanideX** [comment]
![2021-01-24_15 06 04](https://user-images.githubusercontent.com/3106700/105646633-b8c3c180-5e55-11eb-8014-6bb6c9a67eef.png)

Side note: I did fix an issue with the normal map of the iron block. The outer border was mirrored by mistake. 😅
